language: generic
sudo: required
services: docker
env:
  # https://hub.docker.com/_/fedora/
  - CONTAINER_IMAGE=fedora:26 TOXENV=lint-py3,lint-py2,py36,py35,py27
  - CONTAINER_IMAGE=fedora:25 TOXENV=py36
  - CONTAINER_IMAGE=fedora:rawhide TOXENV=py36,py27
  # https://hub.docker.com/r/junaruga/rpm-py-installer-docker/
  - CONTAINER_IMAGE=junaruga/rpm-py-installer-docker:26 TOXENV=intg
  # https://hub.docker.com/_/centos/
  - CONTAINER_IMAGE=centos:7 TOXENV=py34,py27
install:
  - |
    DOCKER_FILE=.travis/Dockerfile
    if [[ "${CONTAINER_IMAGE}" =~ centos ]]; then
        DOCKER_FILE=.travis/Dockerfile.centos
    fi
    export DOCKER_FILE
  - |
    sed -i "/^FROM / s|FROM .*|FROM ${CONTAINER_IMAGE}|" "${DOCKER_FILE}"
  - |
    docker build \
        -t rpm-py-installer \
        -f "${DOCKER_FILE}" \
        .
script:
  - |
    docker run \
        -e TOXENV="${TOXENV}" \
        -t \
        rpm-py-installer
branches:
  only:
    - master
matrix:
  allow_failures:
    - env: CONTAINER_IMAGE=fedora:rawhide TOXENV=py36,py27
  fast_finish: true
