dist: xenial
language: bash
services: docker
git:
  quiet: true
matrix:
  include:
    - env: SERVICE=fedora29
    - env: SERVICE=fedora28
    - env: SERVICE=fedora27
    - env: SERVICE=fedora26
    - env: SERVICE=fedora_rawhide
    - env: SERVICE=intg
    - env: SERVICE=centos7
    - env: SERVICE=centos6
    - env: SERVICE=centos5
    - env: SERVICE=ubuntu_bionic
    - env: SERVICE=ubuntu_trusty
  allow_failures:
    - env: SERVICE=fedora_rawhide
  fast_finish: true
install: |
  travis_retry make build SERVICE=${SERVICE}
script: |
  make test SERVICE=${SERVICE}
branches:
  only:
    - master
