dist: xenial
language: bash
services: docker
git:
  quiet: true
env:
  global:
    - TARGETS="build"
matrix:
  include:
    - env: SERVICE=fedora30
    - env: SERVICE=fedora30_aarch64 TARGETS="qemu build"
    - env: SERVICE=fedora29
    - env: SERVICE=fedora28
    - env: SERVICE=fedora27
    - env: SERVICE=fedora26
    - env: SERVICE=fedora_rawhide
    - env: SERVICE=intg
    - env: SERVICE=centos7
    - env: SERVICE=centos6
    - env: SERVICE=ubuntu_bionic
    - env: SERVICE=ubuntu_trusty
  allow_failures:
    - env: SERVICE=fedora_rawhide
  fast_finish: true
install: |
  travis_retry make ${TARGETS} SERVICE=${SERVICE}
script: |
  make test SERVICE=${SERVICE}
branches:
  only:
    - master
