dist: bionic
language: bash
services: docker
git:
  quiet: true
env:
  global:
    - DOCKER="docker"
    - TARGETS=""
matrix:
  include:
    # https://hub.docker.com/_/fedora/
    # Run multi arch cases on only cron mode at first, as it takes 30+ minutes.
    - name: fedora30_s390x
      env: IMAGE="s390x/fedora:30" TOXENV="py37" TARGETS="qemu build"
      if: type = cron
    - name: fedora30
      env: IMAGE="fedora:30" TOXENV="lint-py3,lint-py2,py37-cov,py27-cov" TEST_LINT="true"
    - name: fedora29
      env: IMAGE="fedora:29"
      if: type = cron
    - name: fedora28
      env: DOCKER="podman" IMAGE="fedora:28" TOXENV="py36"
      script: make no-network-test
    - name: fedora27
      env: IMAGE="fedora:27" TOXENV="py36"
      if: type = cron
    - name: fedora26
      env: IMAGE="fedora:26" TOXENV="py35,py26"
    - name: fedora_rawhide
      env: TOXENV="py37"
    - name: intg
      env: TOXENV="intg"
    # https://hub.docker.com/_/centos/
    - name: centos7
      env: DOCKERFILE="ci/Dockerfile-centos.7" TOXENV="py36-cov,py34-cov,py27-cov"
    - name: centos6
      env: DOCKERFILE="ci/Dockerfile-centos.6" TOXENV="py27,py26"
    # https://hub.docker.com/_/ubuntu/
    - name: ubuntu_bionic
      env: DOCKERFILE="ci/Dockerfile-ubuntu.bionic" TOXENV="py36-cov,py27-cov"
    - name: ubuntu_trusty
      env: DOCKERFILE="ci/Dockerfile-ubuntu.trusty" TOXENV="py34,py27"
    # https://hub.docker.com/r/opensuse/tumbleweed
    - name: opensuse_tumbleweed
      env: DOCKERFILE="ci/Dockerfile-opensuse" IMAGE="opensuse/tumbleweed" TOXENV="py3-cov"
    # https://hub.docker.com/r/opensuse/leap
    - name: opensuse_leap_15
      env: DOCKERFILE="ci/Dockerfile-opensuse" IMAGE="opensuse/leap:15" TOXENV="py36-cov,py27-cov"
  allow_failures:
    - name: fedora_rawhide
  fast_finish: true
before_install:
  - |
    if [ "${DOCKER}" = "podman" ]; then
      ci/install_podman_on_ubuntu.sh
    fi
install: |
  travis_retry make ${TARGETS}
script: |
  make test
branches:
  except:
    # Enable branches except the working in progress branch or
    # current pull-request feature/ci-centos.
    - /^(wip\/|feature\/ci-centos5)/
